# docker compose to build dockerfile and postgresql 
# docker-compose up --build
# docker-compose up

# docker-compose down
version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      DATABASE_NAME: recommendations
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  recommendations:
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    networks:
      - default
    depends_on:
      - db
